name: PocketGate
author: dresnite
api: 5.0.0
version: 1.0.0
main: PocketGate\PocketGate
description: Seamlessly convert your PocketMine-MP worlds into Hytopia’s format, all from within the game.

permissions:
  pocketgate.command:
    description: Allows players open the PocketGate interface
    default: op
  pocketgate.command.pg1:
    description: Sets first player position
    default: op
  pocketgate.command.pg2:
    description: Set second player position
    default: op
  pocketgate.command.pgc:
    description: Starts the conversion process
    default: op